### ISSUE TITLE
SyncUsersで500

### ISSUE THREAD

**Issue by ras0q** [traPtitech/knoQ#504]
```plaintext
knoq_app      | 
knoq_app      | 2023/12/21 09:01:18 /app/infra/db/token.go:19
knoq_app      | [0.827ms] [rows:1] SELECT * FROM `tokens` WHERE `tokens`.`user_id` = '0fa5d740-0841-4b88-b7c8-34a68774c784' LIMIT 1
knoq_app      | 
knoq_app      | 2023/12/21 09:01:18 /app/infra/db/user.go:99
knoq_app      | [0.544ms] [rows:1] SELECT * FROM `providers` WHERE `providers`.`user_id` = '0fa5d740-0841-4b88-b7c8-34a68774c784'
knoq_app      | 
knoq_app      | 2023/12/21 09:01:18 /app/infra/db/user.go:99
knoq_app      | [1.434ms] [rows:1] SELECT * FROM `users` WHERE `users`.`id` = '0fa5d740-0841-4b88-b7c8-34a68774c784' LIMIT 1
knoq_app      | 
knoq_app      | 2023/12/21 09:01:18 /app/infra/db/user.go:99
knoq_app      | [0.625ms] [rows:1] SELECT * FROM `providers` WHERE `providers`.`user_id` = '0fa5d740-0841-4b88-b7c8-34a68774c784'
knoq_app      | 
knoq_app      | 2023/12/21 09:01:18 /app/infra/db/user.go:99
knoq_app      | [1.465ms] [rows:1] SELECT * FROM `users` WHERE `users`.`id` = '0fa5d740-0841-4b88-b7c8-34a68774c784' LIMIT 1
knoq_app      | 
knoq_app      | 2023/12/21 09:01:18 /app/infra/db/user.go:99
knoq_app      | [0.511ms] [rows:1] SELECT * FROM `providers` WHERE `providers`.`user_id` = '0fa5d740-0841-4b88-b7c8-34a68774c784'
knoq_app      | 
knoq_app      | 2023/12/21 09:01:18 /app/infra/db/user.go:99
knoq_app      | [1.171ms] [rows:1] SELECT * FROM `users` WHERE `users`.`id` = '0fa5d740-0841-4b88-b7c8-34a68774c784' LIMIT 1
knoq_app      | 
knoq_app      | 2023/12/21 09:01:18 /app/infra/db/token.go:19
knoq_app      | [0.604ms] [rows:1] SELECT * FROM `tokens` WHERE `tokens`.`user_id` = '0fa5d740-0841-4b88-b7c8-34a68774c784' LIMIT 1
knoq_app      | 
knoq_app      | 2023/12/21 09:01:18 /app/infra/db/user.go:109
knoq_app      | [0.445ms] [rows:1] SELECT * FROM `users`
knoq_app      | 2023-12-21T09:01:18.255+0900    INFO    router/middleware.go:54 server error    {"field": {"requestMethod": "POST", "requestUrl": "/api/users/sync", "requestSize": "0", "status": 500, "responseSize": "47", "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0", "remoteIp": "172.21.0.1", "serverIp": "", "referer": "http://localhost:3000/", "latency": "0.081375194s", "protocol": "HTTP/1.1", "error": "/app/router/users.go:72: unsupported driver"}}
```

**Comment by iChemy** [comment]
fixed by #517

**Comment by iChemy** [comment]
<img width="1440" alt="スクリーンショット 2024-07-03 23 11 29" src="https://github.com/traPtitech/knoQ/assets/104891359/21ac5144-a106-47ed-9250-74f485322fc2">
ステージングで起こった

ローカル開発環境でも起こる (多分本番環境でも起こってそう)
```
{"time":"2024-07-03T23:14:41.748621591+09:00","level":"-","prefix":"echo","file":"recover.go","line":"119","message":"[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 33 [running]:\ngithub.com/traPtitech/knoQ/router.(*Handlers).SetupRoute.Recover.RecoverWithConfig.func4.1.1()\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:99 +0x13c\npanic({0x5c3b00?, 0xb1f7a0?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x124\ngithub.com/traPtitech/knoQ/infra/db.(*dialector).SavePoint(0xb23da0?, 0x63e7a0?, {0x4000398110?, 0x4000412d98?})\n\t<autogenerated>:1 +0x2c\ngorm.io/gorm.(*DB).SavePoint(0x40005400c0, {0x4000398110, 0xa})\n\t/go/pkg/mod/gorm.io/gorm@v1.25.10/finisher_api.go:724 +0xec\ngorm.io/gorm.(*DB).Transaction(0x40005400c0, 0x4000288100, {0x0?, 0x0?, 0x0?})\n\t/go/pkg/mod/gorm.io/gorm@v1.25.10/finisher_api.go:626 +0xc8\ngithub.com/traPtitech/knoQ/infra/db.saveUser(0x40005400c0, 0x40003fa000)\n\t/app/infra/db/user.go:75 +0xb0\ngithub.com/traPtitech/knoQ/infra/db.(*GormRepository).SyncUsers.func1(0x40005400c0)\n\t/app/infra/db/user.go:59 +0xe8\ngorm.io/gorm.(*DB).Transaction(0x4000260ae0, 0x40003e0040, {0x0?, 0x0?, 0x0?})\n\t/go/pkg/mod/gorm.io/gorm@v1.25.10/finisher_api.go:651 +0x1d8\ngithub.com/traPtitech/knoQ/infra/db.(*GormRepository).SyncUsers(0x40000772a0, {0x400052e008, 0x71a, 0x8ff})\n\t/app/infra/db/user.go:35 +0x94\ngithub.com/traPtitech/knoQ/repository.(*Repository).SyncUsers(0x40000772a0, 0x40001c7ef0)\n\t/app/repository/user.go:48 +0x284\ngithub.com/traPtitech/knoQ/router.(*Handlers).HandleSyncUser(0x400032e4e0, {0x766540, 0x40001de5a0})\n\t/app/router/users.go:70 +0x4c\ngithub.com/traPtitech/knoQ/router.(*Handlers).PrivilegeUserMiddleware-fm.(*Handlers).PrivilegeUserMiddleware.func1({0x766540, 0x40001de5a0})\n\t/app/router/middleware.go:117 +0x68\ngithub.com/traPtitech/knoQ/router.(*Handlers).TraQUserMiddleware-fm.(*Handlers).TraQUserMiddleware.func1({0x766540, 0x40001de5a0})\n\t/app/router/middleware.go:101 +0x13c\ngithub.com/labstack/echo/v4.(*Echo).add.func1({0x766540, 0x40001de5a0})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:587 +0x50\ngithub.com/labstack/echo/v4/middleware.StaticWithConfig.func1.1({0x766540, 0x40001de5a0})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/static.go:166 +0x690\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x766540, 0x40001de5a0})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/cors.go:253 +0x490\ngithub.com/traPtitech/knoQ/router.(*Handlers).SetupRoute.ServerVersionMiddleware.func3.1({0x766540, 0x40001de5a0})\n\t/app/router/middleware.go:78 +0x78\ngithub.com/traPtitech/knoQ/router.(*Handlers).SetupRoute.Middleware.MiddlewareWithConfig.func6.1({0x766540, 0x40001de5a0})\n\t/go/pkg/mod/github.com/labstack/echo-contrib@v0.17.1/session/session.go:73 +0xd8\ngithub.com/traPtitech/knoQ/router.(*Handlers).SetupRoute.AccessLoggingMiddleware.func2.1({0x766540, 0x40001de5a0})\n\t/app/router/middleware.go:26 +0x5c\ngithub.com/traPtitech/knoQ/router.(*Handlers).SetupRoute.Secure.SecureWithConfig.func5.1({0x766540, 0x40001de5a0})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/secure.go:141 +0x300\ngithub.com/traPtitech/knoQ/router.(*Handlers).SetupRoute.Recover.RecoverWithConfig.func4.1({0x766540, 0x40001de5a0})\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:130 +0xe8\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0x400036e008, {0x75da60, 0x40005a20e0}, 0x4000000120)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:674 +0x304\nnet/http.serverHandler.ServeHTTP({0x40002a22a0?}, {0x75da60?, 0x40005a20e0?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:3142 +0xbc\nnet/http.(*conn).serve(0x40002ba000, {0x75e9b8, 0x40002a21b0})\n\t/usr/local/go/src/net/http/server.go:2044 +0x508\ncreated by net/http.(*Server).Serve in goroutine 7\n\t/usr/local/go/src/net/http/server.go:3290 +0x3f0\n\ngoroutine 1 [chan receive, 1 minutes]:\nmain.main()\n\t/app/main.go:120 +0x7a8\n\ngoroutine 18 [select, 1 minutes]:\ngithub.com/patrickmn/go-cache.(*janitor).Run(0x40001e1c60, 0x4000223180)\n\t/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0x78\ncreated by github.com/patrickmn/go-cache.runJanitor in goroutine 1\n\t/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xe8\n"}
```

**Comment by iChemy** [comment]
(*dialector).SavePoint() が存在しないから起こってそう．

私が過去に修正した
```go
type dialector struct {
	gorm.Dialector
	gorm.SavePointerDialectorInterface
}
```
が多分ダメ．

まず 
* (*DB)Transaction() が呼ばれる
* 中で (*DB).SavePoint が呼ばれる．

(gorm の finisher_api.go より)
```go
func (db *DB) SavePoint(name string) *DB {
	if savePointer, ok := db.Dialector.(SavePointerDialectorInterface); ok {
		// 省略
		db.AddError(savePointer.SavePoint(db, name))
```
ここで多分 (dialector 構造体の) d に対して d.(SavePointerDialectorInterface) が行われる．

上の dialector の定義を見れば分かるとおりキャストは成功する．
しかし，これをキャストしたときに `savePointer` 変数には何も入っていないのではないか?
というのも

```go
	d := dialector{
		Dialector: mysql.New(mysql.Config{ /*  省略 */ }),
		// SavePointerDialectorInterface: 何も入れられていない
	}
```
で dialector の SavePointerDialectorInterface フィールドには何も入れられていないから

**Comment by iChemy** [comment]
ちなみに mysql.New() の実装は
```go
func New(config Config) gorm.Dialector {
// 省略
	return &Dialector{Config: &config}
}
```
で mysql.Dialector 構造体へのポインタをgorm.Dialector インターフェースとして返している
そして mysql.(*Dialector) は  gorm.SavePointerDialectorInterface も実装しているので
わざわざ dialector 構造体を定義する必要もなく gorm.Open に mysql.New の結果を直に渡して良いはず
```go
	var err error
	repo.db, err = gorm.Open(mysql.New(mysql.Config{
		DSNConfig: &gomysql.Config{
			User:                 user,
			Passwd:               password,
			Net:                  "tcp",
			Addr:                 host + ":" + port,
			DBName:               database,
			Loc:                  loc,
			AllowNativePasswords: true,
			ParseTime:            true,
		},
		DefaultStringSize:         256,   // default size for string fields
		DisableDatetimePrecision:  true,  // disable datetime precision, which not supported before MySQL 5.6
		DontSupportRenameIndex:    true,  // drop & create when rename index, rename index not supported before MySQL 5.7, MariaDB
		DontSupportRenameColumn:   false, // `change` when rename column, rename column not supported before MySQL 8, MariaDB
		SkipInitializeWithVersion: false, // auto configure based on currently MySQL version
	}), &gorm.Config{
		Logger: logger.Default.LogMode(loglevel),
	})
```

**Comment by iChemy** [comment]
ただ，なぜ一回解決しうまく動作してるように見えたのかわからない
